<template>
  <div class="mine">
    Scroll down to see the bottom-right button.

    <ul>
      <li>hh1</li>
      <li>hh2</li>
      <li>hh3</li>
      <li>hh4</li>
      <li>hh5</li>
      <li>hh6</li>
      <li>hh7</li>
      <li>hh8</li>
      <li>hh9</li>
      <li>hh10</li>
      <li>hh11</li>
      <li>hh12</li>
      <li>hh13</li>
      <li>hh14</li>
      <li>hh15</li>
      <li>hh16</li>
      <li>hh17</li>
      <li>hh18</li>
      <li>hh19</li>
      <li>hh20</li>
      <li>hh21</li>
      <li>hh22</li>
      <li>hh23</li>
      <li>hh24</li>
      <li>hh25</li>
      <li>hh26</li>
      <li>hh27</li>
      <li>hh28</li>
      <li>hh29</li>
      <li>hh30</li>
      <li>hh31</li>
      <li>hh32</li>
      <li>hh33</li>
      <li>hh34</li>
      <li>hh35</li>
      <li>hh36</li>
      <li>hh37</li>
      <li>hh38</li>
      <li>hh39</li>
      <li>hh40</li>
      <li>hh41</li>
      <li>hh42</li>
      <li>hh43</li>
      <li>hh44</li>
      <li>hh45</li>
      <li>hh46</li>
      <li>hh47</li>
      <li>hh48</li>
      <li>hh49</li>
      <li>hh50</li>
      <li>hh51</li>
      <li>hh52</li>
      <li>hh53</li>
      <li>hh54</li>
      <li>hh55</li>
      <li>hh56</li>
      <li>hh57</li>
      <li>hh58</li>
      <li>hh59</li>
      <li>hh60</li>
      <li>hh61</li>
      <li>hh62</li>
      <li>hh63</li>
      <li>hh64</li>
      <li>hh65</li>
      <li>hh66</li>
      <li>hh67</li>
      <li>hh68</li>
      <li>hh69</li>
      <li>hh70</li>
      <li>hh71</li>
      <li>hh72</li>
      <li>hh73</li>
      <li>hh74</li>
      <li>hh75</li>
      <li>hh76</li>
      <li>hh77</li>
      <li>hh78</li>
      <li>hh79</li>
      <li>hh80</li>
      <li>hh81</li>
      <li>hh82</li>
      <li>hh83</li>
      <li>hh84</li>
      <li>hh85</li>
      <li>hh86</li>
      <li>hh87</li>
      <li>hh88</li>
      <li>hh89</li>
      <li>hh90</li>
      <li>hh91</li>
      <li>hh92</li>
      <li>hh93</li>
      <li>hh94</li>
      <li>hh95</li>
      <li>hh96</li>
      <li>hh97</li>
      <li>hh98</li>
      <li>hh99</li>
      <li>hh100</li>
    </ul>
    <el-backtop target=".mine" :visibility-height="10" :bottom="70"></el-backtop>
  </div>
</template>

<script>
export default {

}
</script>

<style>
.mine {
  height: 100vh;
  overflow-x: hidden;
}
</style>
